# a double between 0 to 1 that describes the ideal percentage of players you want on each game server
server_target_capacity: 0.8

# Redis database connection
host: 0.0.0.0
port: 6379
username: your redis username
password: your redis password